application: map-it-clean
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /styles
  static_dir: styles

- url: /scripts
  static_dir: scripts

- url: /content
  static_dir: content

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
